version: '3.1'

services:
  app:
    build: .
    command: ["./wait-for-it.sh", "neo4j:7687", "--", "python", "import_queries.py"]
    env_file:
      - .env
    depends_on:
      - neo4j
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data:/data
    environment:
      NEO4J_AUTH: ${NEO4J_USER}/${NEO4J_PASSWORD}